spring.application.name=plantcare-backend

# PostgreSQL — ajustar quando o docker-compose estiver rodando
spring.datasource.url=jdbc:postgresql://localhost:5433/plantcare
spring.datasource.username=plantcare
spring.datasource.password=plantcare

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

jwt.secret=plantcare-secret-key-deve-ter-256-bits-minimo-para-hs256-seguranca
jwt.expiration=86400000
